spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: t1-spring-security
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true


jwt:
  secret: ${JWT_SECRET}
  tokenExpiration: 10m
  refreshTokenExpiration: 100m